package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"

	model1 "github.com/Elbujito/2112/graphql-api/graph/model"
)

// SatellitePosition is the resolver for the satellitePosition field.
func (r *queryResolver) SatellitePosition(ctx context.Context, id string) (*model1.SatellitePosition, error) {
	panic(fmt.Errorf("not implemented: SatellitePosition - satellitePosition"))
}

// SatelliteTle is the resolver for the satelliteTle field.
func (r *queryResolver) SatelliteTle(ctx context.Context, id string) (*model1.SatelliteTle, error) {
	panic(fmt.Errorf("not implemented: SatelliteTle - satelliteTle"))
}

// SatellitePositionsInRange is the resolver for the satellitePositionsInRange field.
func (r *queryResolver) SatellitePositionsInRange(ctx context.Context, id string, startTime string, endTime string) ([]*model1.SatellitePosition, error) {
	panic(fmt.Errorf("not implemented: SatellitePositionsInRange - satellitePositionsInRange"))
}

// SatellitePositionUpdated is the resolver for the satellitePositionUpdated field.
func (r *subscriptionResolver) SatellitePositionUpdated(ctx context.Context, id string) (<-chan *model1.SatellitePosition, error) {
	panic(fmt.Errorf("not implemented: SatellitePositionUpdated - satellitePositionUpdated"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) MessageHistory(ctx context.Context) ([]string, error) {
	panic(fmt.Errorf("not implemented: MessageHistory - messageHistory"))
}
func (r *subscriptionResolver) MessageReceived(ctx context.Context) (<-chan string, error) {
	panic(fmt.Errorf("not implemented: MessageReceived - messageReceived"))
}
*/
