global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "app-service"
    static_configs:
      - targets: ["app-service:8080"]
    metrics_path: /metrics
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://app-service:8081/health/alive
        - http://app-service:8081/health/ready
        - http://propagator-service:5000/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

remote_write:
  - url: "http://periscope:4100/ingest"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: "profiling.*"
        action: keep