COMPOSE_FILE=ci/compose/postgres.yaml

.PHONY: up down restart logs build

up:
	docker-compose -f $(COMPOSE_FILE) up -d

down:
	docker-compose -f $(COMPOSE_FILE) down

restart:
	docker-compose -f $(COMPOSE_FILE) down
	docker-compose -f $(COMPOSE_FILE) up -d

logs:
	docker-compose -f $(COMPOSE_FILE) logs -f

build:
	docker-compose -f $(COMPOSE_FILE) build