services:
  2112-web:
    build:
      context: .
      dockerfile: ci/docker/Dockerfile.web
    image: 2112-web
    container_name: 2112-web
    ports:
      - "3000:3000"
    restart: unless-stopped
