version: "3.8"

services:
  satellite-server:
    build:
      context: ../.. # Adjust this to the root directory
      dockerfile: ci/docker/Dockerfile.python
    container_name: satellite_server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: always
