version: "3.8"

services:
  # Main Application Service
  2112-service:
    build:
      context: ../../.
      dockerfile: ci/docker/Dockerfile # Path to the Dockerfile relative to the context
    container_name: 2112-service # Assign a name to the container
    env_file: ../config/2112/2112.dev-env
    ports:
      - "8081:8081"
      - "8080:8080"
      - "8079:8079"
    depends_on:
      2112-db-seeder:
        condition: service_completed_successfully
    restart: always # Restart the container on failure
    command: ["service", "start"]