version: "3.8"

services:
  2112-service:
    build:
      context: .
      dockerfile: ci/docker/Dockerfile # Path to the Dockerfile relative to the context
      args:
    container_name: 2112-service # Assign a name to the container
    env_file: ../config/2112/2112.dev-env
    ports:
      - "8081:8081"
      - "8080:8080"
      - "8079:8079"
    restart: always # Restart the container on failure
