version: "3.8"

services:
  2112-propagator:
    build:
      context: ../.. # Adjust context to the project root
      dockerfile: ci/docker/Dockerfile.python # Path to the Dockerfile relative to the context
    container_name: 2112-propagator # Assign a name to the container
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    restart: always # Restart the container on failure
