version: "3.8"

services:
  propagator-server:
    build:
      context: ../.. # Adjust context to the project root
      dockerfile: ci/docker/Dockerfile.python # Path to the Dockerfile relative to the context
      args:
        PYTHON_EXECUTABLE_NAME: propagator_server # Pass the executable name as a build argument
    container_name: propagator_server # Assign a name to the container
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    restart: always # Restart the container on failure
