# This workflow will build a Go project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build Workflow

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # Cache Go modules to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: |
          cd src/app-service
          go mod tidy

      # Build the application
      - name: Build the application
        run: |
          cd src/app-service/internal
          go build -o ./out/service .

      # (Optional) Run tests
      - name: Run tests
        run: |
          cd src/app-service/internal
          go test -v ./...

