version: '3.8'

services:
  # web:
  #   build:
  #     context: ../../.
  #     dockerfile: deployments/docker/Dockerfile.web
  #   image: web
  #   container_name: web
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped