version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./assets/rabbitmq/data:/var/lib/rabbitmq
      - ./assets/rabbitmq/log:/var/log/rabbitmq

  # keycloak:
  #   container_name: keycloak
  #   build:
  #     context: ../../.
  #     dockerfile: deployments/docker/Dockerfile.keycloak
  #   environment:
  #     - KEYCLOAK_USER=admin
  #     - KEYCLOAK_PASSWORD=admin
  #     - DB_VENDOR=h2
  #   ports:
  #     - "8086:8080"

networks:
  default:
    name: 2112_net
    external: true
