services:
  dev-service:
    container_name: dev-service
    build:
      context: ./
      dockerfile: ./deployments/docker/Dockerfile.dev
    ports:
      - "8081:8081"
      - "8080:8080"
      - "8079:8079"
    env_file: ./deployments/config/app.dev-env
    volumes:
      - ./:/app
    command:
      - air
      - --build.bin
      - "./tmp/main start -d -e -H 0.0.0.0"
