version: '3.8'
services:
  postgres-db:
    build:
      context: ../../.
      dockerfile: deployments/docker/Dockerfile.postgres
    container_name: postgres-db
    ports:
      - "5440:5432"
    env_file: ../config/postgres.dev-env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
