version: "3.7"
services:
  postgres-db:
    image: postgis/postgis:latest
    container_name: postgres-db
    ports:
      - "5440:5432"
    env_file: ../config/postgres.dev-env
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
